/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2022-05-18 00:28:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.adopt;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".subject {\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\tcolor: gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row {\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tmargin:10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row:hover {\r\n");
      out.write("\tcursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row:hover > .adopt_title {\r\n");
      out.write("\ttransition: display .5s;\r\n");
      out.write("\tdisplay:block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".adopt_img {\r\n");
      out.write("\twidth : 300px;\r\n");
      out.write("\theight : 330px;\r\n");
      out.write("\tz-index:-1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tbl_adopt {\r\n");
      out.write("\twidth:1400px;\r\n");
      out.write("\tmargin:0px auto;\r\n");
      out.write("\tpadding-left:50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".adopt_title {\r\n");
      out.write("\tdisplay:none;\r\n");
      out.write("\twidth:300px;\r\n");
      out.write("\tbackground:black;\r\n");
      out.write("\topacity: 0.5;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tpadding:10px;\r\n");
      out.write("\ttransform: translateY(-40px);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<div style=\"text-align:center;position: relative; margin-bottom:70px;\">\r\n");
      out.write("\t<img src=\"/resources/adopt_banner.png\" style=\"height:500px; width:100%;\">\r\n");
      out.write("\t<div class=\"body_banner\"> \r\n");
      out.write("\t\t<div class=\"heading\">\r\n");
      out.write("\t\t  <div>\r\n");
      out.write("\t\t    <p id=\"banner_top\" class=\"slide-up\">입양 & 분양</p>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"notosanskr\">\r\n");
      out.write("\t\t    <p id=\"banner_bottom\" class=\"slide-up\">포포펫의 반려동물들의 분양 목록을 알려드립니다</p>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div> \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"page\">\r\n");
      out.write("\t<p class=\"small_title\">분양중인 아이들</p>\r\n");
      out.write("\t<p class=\"big_title\">포포펫의 아이들을 소개해드립니다 </p>\r\n");
      out.write("\t<div id=\"tbl_adopt\"></div>\r\n");
      out.write("\t<script id=\"temp\" type=\"text/x-handlebars-template\"> \r\n");
      out.write("      {{#each list}}\r\n");
      out.write("      <div class=\"row\" onClick=\"location.href='/adopt/read?ano={{ano}}'\">\r\n");
      out.write("\t\t <img src=\"/display?fileName={{image}}\" class=\"adopt_img\">\r\n");
      out.write("\t\t <div class=\"adopt_title\">{{kinds}} - {{title}}</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      {{/each}}\r\n");
      out.write("   </script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tHandlebars.registerHelper(\"display\", function(price) {\r\n");
      out.write("\t\t\treturn price.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ',');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<div class=\"pagination\"></div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<input type=\"text\" id=\"keyword\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.keyword }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"검색\" id=\"search\">\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("   var page=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.page==null?1:param.page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("   var keyword=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.keyword==null?'':param.keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("   getList();\r\n");
      out.write("   \r\n");
      out.write("   //인서트이동\r\n");
      out.write("   $(\"#insert\").on(\"click\",function(){\r\n");
      out.write("\t\tlocation.href = \"insert\";\r\n");
      out.write("\t});\r\n");
      out.write("   \r\n");
      out.write("   function getList(){\r\n");
      out.write("      keyword= $(\"#keyword\").val();\r\n");
      out.write("      $.ajax({\r\n");
      out.write("         type: \"get\",\r\n");
      out.write("         url: \"/adopt/list.json\",\r\n");
      out.write("         data: {page:page, keyword:keyword},\r\n");
      out.write("         dataType: \"json\",\r\n");
      out.write("         success:function(data){\r\n");
      out.write("            var temp = Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("            $(\"#tbl_adopt\").html(temp(data));\r\n");
      out.write("            //페이지목록출력\r\n");
      out.write("             $(\".pagination\").html(getPagination(data));     \r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   //페이지 번호를 클릭한 경우\r\n");
      out.write("   $(\".pagination\").on(\"click\", \"a\", function(e){\r\n");
      out.write("      e.preventDefault();\r\n");
      out.write("      page=$(this).attr(\"href\");\r\n");
      out.write("      getList();\r\n");
      out.write("   });\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
