/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2022-05-18 01:21:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class complete_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\n");
      out.write("<link href=\"/resources/join.css\" rel=\"stylesheet\" >\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("\tarticle {\n");
      out.write("\t\ttext-align:center; border: 1px solid #aeaeae; width:1200px;\n");
      out.write("\t\tmargin : 0px auto;\n");
      out.write("\t\tmargin-top:100px;\n");
      out.write("\t\tborder-radius:50px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.footer {\n");
      out.write("\t\ttext-align:center;\n");
      out.write("\t\tfont-family: 'SBAggroL';\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.footer button {\n");
      out.write("\t\tpadding:20px;\n");
      out.write("\t\tbackground:#232323;\n");
      out.write("\t\tcolor:white;\n");
      out.write("\t\tmargin-top:50px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.small_title {\n");
      out.write("\t\tmargin-top:10px;\n");
      out.write("\t}\n");
      out.write("</style>\n");
      out.write("<div style=\"text-align:center;position: relative;\">\n");
      out.write("\t<img src=\"/resources/join_img/join_banner.png\" style=\"height:500px; width:100%;\">\n");
      out.write("\t<div class=\"body_banner\"> \n");
      out.write("\t\t<div class=\"heading\">\n");
      out.write("\t\t  <div>\n");
      out.write("\t\t    <p id=\"banner_top\" class=\"slide-up\">회원가입</p>\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t  <div class=\"notosanskr\">\n");
      out.write("\t\t    <p id=\"banner_bottom\" class=\"slide-up\">새로운 인연,포포펫에서 함께 만들어 가겠습니다</p>\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div> \n");
      out.write("</div>\n");
      out.write("<article>\n");
      out.write("\t<img src=\"/resources/check.png\" width=100 style=\"margin-top:50px;\">\n");
      out.write("\t<p class=\"small_title\">회원가입이 완료되었습니다.</p>\n");
      out.write("\t<p class=\"big_title\">포포펫에서 새로운 인연을 찾아가세요.</p>\n");
      out.write("</article>\n");
      out.write("<div class=\"footer\">\n");
      out.write("   <button onClick=\"location.href='/'\">메인으로 가기</button>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\t\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
