/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2022-05-19 01:21:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class find_005fid_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<style>\n");
      out.write("\t#banner_top {\n");
      out.write("\t\tmargin-left:120px;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("   .modal3 {\n");
      out.write("      position: absolute;\n");
      out.write("      top: 0;\n");
      out.write("      left: 0;\n");
      out.write("      width: 100%;\n");
      out.write("      height: 1600px;\n");
      out.write("      display: none;\n");
      out.write("      background-color: rgba(0, 0, 0, 0.4);\n");
      out.write("      z-index: 10;\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   .modal_body3 {\n");
      out.write("      position: absolute;\n");
      out.write("      top: 50%;\n");
      out.write("      left: 50%;\n");
      out.write("      width: 800px;\n");
      out.write("      height: 300px;\n");
      out.write("      text-align: center;\n");
      out.write("      background-color: rgb(255, 255, 255);\n");
      out.write("      border-radius: 10px;\n");
      out.write("      box-shadow: 0 2px 3px 0 rgba(34, 36, 38, 0.15);\n");
      out.write("      transform: translateX(-50%) translateY(-20%);\n");
      out.write("      z-index: 10;\n");
      out.write("      margin: 0px auto;\n");
      out.write("      padding: 40px;\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   .btn-close3 {\n");
      out.write("      width: 20px;\n");
      out.write("      height: 20px;\n");
      out.write("      float: right;\n");
      out.write("      cursor: pointer;\n");
      out.write("   }\n");
      out.write("   .searchSelect_box {\n");
      out.write("   \t  font-size:20px;\n");
      out.write("   \t  font-family: 'SBAggroL';\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   .searchBox {\n");
      out.write("   \t  border:1px solid #aeaeae;\n");
      out.write("   \t  width:600px;\n");
      out.write("   \t  padding:40px;\n");
      out.write("   \t  margin:0px auto;\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   .searchBox input {\n");
      out.write("   \t  border:none;\n");
      out.write("   \t  border-bottom:1px solid #aeaeae;\n");
      out.write("   \t  font-size:17px;\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   .searchBtn {\n");
      out.write("   \t  border:none;\n");
      out.write("   \t  background:#232323;\n");
      out.write("   \t  color:white;\n");
      out.write("   \t  width:400px;\n");
      out.write("   \t  font-size:18px;\n");
      out.write("   \t  padding : 20px;\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   .form-group label {\n");
      out.write("   \t  transform: translateX(-160px);\n");
      out.write("   }\n");
      out.write("</style>\n");
      out.write("<div style=\"text-align:center;position: relative;\">\n");
      out.write("\t<img src=\"/resources/join_img/join_banner.png\" style=\"height:500px; width:100%;\">\n");
      out.write("\t<div class=\"body_banner\"> \n");
      out.write("\t\t<div class=\"heading\">\n");
      out.write("\t\t  <div>\n");
      out.write("\t\t    <p id=\"banner_top\" class=\"slide-up\">ID/PW 찾기</p>\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t  <div class=\"notosanskr\">\n");
      out.write("\t\t    <p id=\"banner_bottom\" class=\"slide-up\">새로운 인연,포포펫에서 함께 만들어 가겠습니다</p>\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div> \n");
      out.write("</div>\n");
      out.write("<div class=\"full\">\n");
      out.write("   <div class=\"container\">\n");
      out.write("         <p class=\"small_title\">아이디/비밀번호 찾기</p>\t\n");
      out.write("\t\t <p class=\"big_title\">ID/PW 찾기</p>\n");
      out.write("         <div class=\"searchSelect_box\">\n");
      out.write("            <input type=\"radio\" id=\"search_1\" name=\"search_total\" onclick=\"search_check(1)\" checked=\"checked\">\n");
      out.write("            <label style=\"margin-right:50px;\">아이디&nbsp;찾기</label>\n");
      out.write("            <input type=\"radio\" id=\"search_2\" name=\"search_total\" onclick=\"search_check(2)\"> \n");
      out.write("            <label>비밀번호 찾기</label>\n");
      out.write("         </div>\n");
      out.write("         \n");
      out.write("         <div id=\"searchId\" class=\"searchBox\">\n");
      out.write("         \t<h1>아이디 찾기</h1>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("               \t<label>가입 이메일</label>\n");
      out.write("               <div>\n");
      out.write("                  <input type=\"text\" id=\"uemail\" name=\"uemail\" placeholder=\"ex) E-mail@gmail.com\" size=40>\n");
      out.write("               </div>\n");
      out.write("               <span id=\"email_check\"></span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("               <button id=\"searchBtn\" type=\"button\" onClick=\"findId();\" class=\"searchBtn\">아이디찾기</button>\n");
      out.write("            </div>\n");
      out.write("         </div>\n");
      out.write("         \n");
      out.write("         <div id=\"searchPass\" style=\"display: none;\" class=\"searchBox\">\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("               <label >아이디</label>\n");
      out.write("               <div>\n");
      out.write("                  <input type=\"text\" id=\"userid\" name=\"userid\" placeholder=\"ex) red\" size=40>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("               <label>이메일</label>\n");
      out.write("               <div>\n");
      out.write("                  <input type=\"email\" id=\"uemail2\" name=\"uemail2\" placeholder=\"ex) E-mail@gmail.com\" size=40>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("               <button id=\"searchBtn2\" type=\"button\" class=\"searchBtn\">비밀번호 찾기</button>\n");
      out.write("            </div>\n");
      out.write("         </div>\n");
      out.write("   </div>\n");
      out.write("</div>\n");
      out.write("<button class=\"btn-open-popup3\" style=\"display:none;\">열기</button>\n");
      out.write("<div class=\"modal3\">\n");
      out.write("   <div class=\"modal_body3\">\n");
      out.write("   <img src=\"/resources/cancel.png\" class=\"btn-close3\">\n");
      out.write("      <h1>회원님의 ID는</h1>\n");
      out.write("      <div style=\"font-size:30px;\" id=\"find_id\"></div>\n");
      out.write("      <h1>입니다.</h1>\n");
      out.write("            \n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<script>\n");
      out.write("   function search_check(num) {\n");
      out.write("      if (num == '1') {\n");
      out.write("         document.getElementById(\"searchPass\").style.display = \"none\";\n");
      out.write("         document.getElementById(\"searchId\").style.display = \"\";   \n");
      out.write("      } else {\n");
      out.write("         document.getElementById(\"searchId\").style.display = \"none\";\n");
      out.write("         document.getElementById(\"searchPass\").style.display = \"\";\n");
      out.write("      }\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   function findId() {\n");
      out.write("      var uemail=$(\"#uemail\").val();\n");
      out.write("         if(uemail==\"\"){\n");
      out.write("         alert(\"E-MAIL을 입력하세요!\")\n");
      out.write("          $(\"#uemail_check\").html();\n");
      out.write("          $(\"#uemail\").focus();\n");
      out.write("          return;\n");
      out.write("         }\n");
      out.write("      $.ajax({\n");
      out.write("         type: \"post\",\n");
      out.write("         url: \"/user/idsearch\",\n");
      out.write("         data: {uemail:uemail},\n");
      out.write("         success:function(data){\n");
      out.write("            if(data==\"\"){\n");
      out.write("               alert(\"이메일 없음\");\n");
      out.write("               return;\n");
      out.write("            }else {\n");
      out.write("               $(\"#find_id\").html(data);\n");
      out.write("               modal3.style.display = 'block';\n");
      out.write("            }\n");
      out.write("         }\n");
      out.write("      });\n");
      out.write("   }\n");
      out.write("   //검색어상자에서 엔터를 친경우\n");
      out.write("   $(\"#uemail\").on(\"keypress\", function(e) {\n");
      out.write("      if (e.keyCode == 13)\n");
      out.write("      $(\"#searchBtn\").click();\n");
      out.write("   });\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("<script>\n");
      out.write("   $(\"#searchBtn2\").on(\"click\", function() {\n");
      out.write("      var userid=$(\"#userid\").val();\n");
      out.write("      var uemail2=$(\"#uemail2\").val();\n");
      out.write("      $.ajax({\n");
      out.write("         type: \"post\",\n");
      out.write("         url: \"/user/newpass\",\n");
      out.write("         data: {uid:userid, uemail:uemail2},\n");
      out.write("         success: function(data){\n");
      out.write("            if(userid==\"\"){\n");
      out.write("               alert(\"ID를 입력해주세요!\");\n");
      out.write("               $(\"#userid\").focus();\n");
      out.write("            }else if(uemail2==\"\"){\n");
      out.write("               alert(\"E-MAIL을 입력해주세요!\");\n");
      out.write("               $(\"#uemail2\").focus();\n");
      out.write("            }else{\n");
      out.write("               if(data==1){\n");
      out.write("                  alert(\"해당 아이디의 가입 정보가 없습니다.\");\n");
      out.write("               }else if(data==2){\n");
      out.write("                  alert(\"해당 이메일의 가입 정보가 없습니다.\");\n");
      out.write("               }else{\n");
      out.write("                  location.href=\"/user/newpass?uid=\" + userid;\n");
      out.write("               }               \n");
      out.write("            }            \n");
      out.write("         }\n");
      out.write("      });\n");
      out.write("   });\n");
      out.write("</script>\n");
      out.write("<script>\n");
      out.write("   const\n");
      out.write("   modal3 = document.querySelector('.modal3');\n");
      out.write("   const\n");
      out.write("   btnclose3 = document.querySelector('.btn-close3');\n");
      out.write("   const\n");
      out.write("   btnOpenPopup3 = document.querySelector('.btn-open-popup3');\n");
      out.write("   btnOpenPopup3.addEventListener('click', function() {\n");
      out.write("      modal3.style.display = 'block';\n");
      out.write("   });\n");
      out.write("\n");
      out.write("   btnclose3.addEventListener('click', function() {\n");
      out.write("      modal3.style.display = 'none';\n");
      out.write("   });\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
