/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2022-05-18 01:20:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_005fsel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\n");
      out.write("<link href=\"/resources/join.css\" rel=\"stylesheet\" >\n");
      out.write("<style>\n");
      out.write(".title {\n");
      out.write("\tfont-size:30px;\n");
      out.write("\tmargin : 10px 10px 10px 470px;\n");
      out.write("\tcolor:#4A4A4A;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".owner{\n");
      out.write("\twidth: 150px; height : 150px; border-radius:50px; border: 4px solid #A0A0A0;\n");
      out.write("\tmargin:40px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".select_box {\n");
      out.write("\tmargin: 0px auto;\n");
      out.write("\twidth:400px; \n");
      out.write("\theight: 600px;\n");
      out.write("\tborder:5px solid #C0C0C0;\n");
      out.write("\ttext-align:center;\n");
      out.write("\tpadding: 60px 0px 20px 0px;\n");
      out.write("\tfont-size:15px;\n");
      out.write("\tcolor:#707070;\n");
      out.write("\tfloat : left;\n");
      out.write("\tmargin : 20px;\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=button] {\n");
      out.write("\tborder:1px solid #343434;\n");
      out.write("\tborder-radius:20px;\n");
      out.write("\tbackground:#343434;\n");
      out.write("\tcolor:white;\n");
      out.write("\twidth: 200px;\t\n");
      out.write("\tfont-weight:bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=button]:hover {\n");
      out.write("\tbackground:white;\n");
      out.write("\tcolor:#343434;\n");
      out.write("\ttransition: background-color .5s;\n");
      out.write("\tcursor: pointer;\n");
      out.write("}\n");
      out.write("\t\n");
      out.write(".join_title {\n");
      out.write("\tfont-size:40px;\n");
      out.write("\tfont-weight:50px;\n");
      out.write("\tmargin:auto;\n");
      out.write("\ttext-align:center;\n");
      out.write("\tmargin : 100px 0px 10px 0px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#join .title {\n");
      out.write("\twidth:975.5px;\n");
      out.write("\tfont-size:30px;\n");
      out.write("\tcolor:#4A4A4A;\n");
      out.write("\tmargin-left: 470px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<form name=\"frm\" id=\"join\">\n");
      out.write("\t<p class=\"join_title\"><span style=\"font-size:18px;\">회원가입</span><br>CREATE ACCOUNT</p>\n");
      out.write(" \t<div style=\"display:flex; justify-content:center;\">\n");
      out.write(" \t\t<div class=\"select_box\">\n");
      out.write("\t \t\t<b><p style=\"font-size:30px; color:#343434; font-weight:800px;\">펫오너</p></b>\n");
      out.write("\t \t\t<p> 진료비와 질병 데이터베이스 </p>\n");
      out.write("\t \t\t<p>조회 및 무료나눔 혜택을 위해 </p>\n");
      out.write("\t \t\t<p>지금 바로 가입하세요. </p>\n");
      out.write("\t \t\t<img src=\"/resources/join_img/owner.png\" class=\"owner\"><br>\n");
      out.write("\t \t\t<input type=\"button\" value=\"펫오너로 가입\" onClick=\"location.href='/user/join'\">\n");
      out.write("\t \t</div>\n");
      out.write("\t</div>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\t//주소 검색후 값 적용\n");
      out.write("\t$(\"#btn_search\").on(\"click\", function(){\n");
      out.write("\t\tnew daum.Postcode({\n");
      out.write("\t\t\toncomplete: function(data){\n");
      out.write("\t\t\t\tconsole.log(data);\n");
      out.write("\t\t\t\t$(frm.uaddress2).val(data.address);\n");
      out.write("\t\t\t\t$(frm.uaddress1).val(data.zonecode);\n");
      out.write("\t\t\t\t$(frm.address1).focus();\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}).open();\t\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$(frm.file).on(\"change\",function(e){\n");
      out.write("\t      var file=$(frm.file)[0].files[0];\n");
      out.write("\t      $(\"#uimage\").attr(\"src\", URL.createObjectURL(file));\n");
      out.write("\t   });\n");
      out.write("\t   \n");
      out.write("\t   $(\"#uimage\").on(\"click\",function(){\n");
      out.write("\t      $(frm.file).click();\n");
      out.write("\t   });\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
