/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2022-05-18 00:28:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<style>\n");
      out.write("\t#login td {\n");
      out.write("\t\tpadding : 10px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#login .btn {\n");
      out.write("\t\twidth : 350px;\n");
      out.write("\t\tpadding : 15px;\n");
      out.write("\t\tfont-size: 15px;\n");
      out.write("\t\tmargin :0px auto;\n");
      out.write("\t\tbackground : #343434;\n");
      out.write("\t\tcolor:white;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#login input:focus { \n");
      out.write("\t\toutline:none;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#login input {\n");
      out.write("\t\tborder :none;\n");
      out.write("\t\tborder-bottom:1px solid #D0D0D0;\n");
      out.write("\t\tfont-size:16px;\n");
      out.write("\t\tpadding : 10px 10px 10px 0px;\n");
      out.write("\t\thint-color:black;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tsmall {\n");
      out.write("\t\tcolor : #C0C0C0;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.login_title {\n");
      out.write("\t\tfont-weight:50px;\n");
      out.write("\t\ttext-align:center;\n");
      out.write("\t\tfont-size:40px;\n");
      out.write("\t\tmargin:10px 0px 20px 0px;\n");
      out.write("\t}\n");
      out.write("</style>\n");
      out.write("<form name=\"frm\" id=\"login\">\n");
      out.write("\t<p class=\"login_title\">로그인</p>\n");
      out.write("\t<table style=\"margin:0px auto;\">\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td>\n");
      out.write("\t\t\t\t<small class=\"titles\">아이디</small><br>\t\t\t\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"login_uid\" name=\"uid\" placeholder=\"아이디\" size=35>\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td>\n");
      out.write("\t\t\t\t<small class=\"titles\">비밀번호</small><br>\t\t\t\n");
      out.write("\t\t\t\t<input type=\"password\" id=\"login_upass\" name=\"upass\" placeholder=\"비밀번호\" size=35>\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr style=\"padding:10px;\">\n");
      out.write("\t\t\t<td>\n");
      out.write("\t\t\t\t<input type=\"checkbox\"> 아이디 저장\n");
      out.write("\t\t\t\t<a href=\"/user/find_id\" style=\"float:right;\">아이디/비밀번호 찾기</a>\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td>\n");
      out.write("\t\t\t\t<button class=\"btn\" id=\"btn_login\">로그인</button>\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td>\n");
      out.write("\t\t\t\t<a href=\"/user/join_sel\" style=\"float:right;\">회원가입</a>\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\n");
      out.write("\t</table>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\t$(\"#btn_login\").on(\"click\", function(e){\n");
      out.write("\t\te.preventDefault();\n");
      out.write("\t\tvar uid=$(\"#login_uid\").val();\n");
      out.write("\t\tvar upass=$(\"#login_upass\").val();\n");
      out.write("\t\t\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\ttype: \"post\",\n");
      out.write("\t\t\turl: \"/user/login\",\n");
      out.write("\t\t\tdata: {uid:uid, upass:upass},\n");
      out.write("\t\t\tsuccess: function(data){\n");
      out.write("\t\t\t\tif(data==0) {\n");
      out.write("\t\t\t\t\talert(\"아이디가 존재하지 않습니다.\");\n");
      out.write("\t\t\t\t}else if(data==2){\n");
      out.write("\t\t\t\t\talert(\"비밀번호가 일치하지 않습니다.\");\n");
      out.write("\t\t\t\t}else {\n");
      out.write("\t\t\t\t\tvar dest=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dest}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("\t\t\t\t\tif(dest==null || dest==\"\"){\n");
      out.write("\t\t\t\t\t\tlocation.href=\"/\";\n");
      out.write("\t\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\tlocation.href=dest;\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
