/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2022-05-18 00:30:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.shop;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class read_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1647577167351L));
    _jspx_dependants.put("jar:file:/C:/git/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project01/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t#tbl_cart {\r\n");
      out.write("\t\tdisplay:flex;\r\n");
      out.write("\t\tjustify-content:center;\r\n");
      out.write("\t\tmargin-top:100px;\r\n");
      out.write("\t\tborder: 1px solid #dedede;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.title {\r\n");
      out.write("\t\tfont-size:25px;\r\n");
      out.write("\t\tfont-weight:400px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.price {\r\n");
      out.write("\t\tfont-size:25px;\r\n");
      out.write("\t\tfont-weight:bold;\r\n");
      out.write("\t\tcolor:#f5602a;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#tbl_cart a {\r\n");
      out.write("\t\tfont-size:17px;\r\n");
      out.write("\t\tbackground:white;\r\n");
      out.write("\t\tpadding:21px 31px;\r\n");
      out.write("\t\tcolor:black;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#tbl_cart a:hover {\r\n");
      out.write("\t\ttext-decoration:none;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.cartIn {\r\n");
      out.write("\t\twidth:150px;\r\n");
      out.write("\t\tfont-size:18px;\r\n");
      out.write("\t\tborder: 1px solid gray;\r\n");
      out.write("\t\tbackground:white;\r\n");
      out.write("\t\tpadding:18px;\r\n");
      out.write("\t\tbackground:#232323;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("<div style=\"text-align:center;position: relative; margin-bottom:70px;\">\r\n");
      out.write("\t<img src=\"/resources/shop_banner.png\" style=\"height:500px; width:100%;\">\r\n");
      out.write("\t<div class=\"body_banner\"> \r\n");
      out.write("\t\t<div class=\"heading\">\r\n");
      out.write("\t\t  <div>\r\n");
      out.write("\t\t    <p id=\"banner_top\" class=\"slide-up\">상품구매</p>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"notosanskr\">\r\n");
      out.write("\t\t    <p id=\"banner_bottom\" class=\"slide-up\">반려동물을 위한 다양한 상품들을 구매하세요</p>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div> \r\n");
      out.write("</div>\r\n");
      out.write("<div style=\"text-align:center;\">\r\n");
      out.write("\t<p class=\"small_title\">상품 구매</p>\r\n");
      out.write("\t<p class=\"big_title\">Buy</p>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("   <!--<span><a href=\"/shop/update?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">정보수정</a></span>-->\r\n");
      out.write("   <form name=\"cart\" id=\"cartIn\" method=\"post\" action=\"insert\" enctype=\"multipart/form-data\">\r\n");
      out.write("      <div id=\"tbl_cart\">\r\n");
      out.write("\t   \t\t<img src=\"/display?fileName=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" width=400>\r\n");
      out.write("\t\t   <table width=500>\r\n");
      out.write("\t\t   \t\t<tr>\r\n");
      out.write("\t\t   \t\t\t<td><div class=\"title\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div><hr></td>\t\r\n");
      out.write("\t\t   \t\t</tr>\r\n");
      out.write("\t\t   \t\t<tr>\r\n");
      out.write("\t\t   \t\t\t<td><div class=\"price\" style=\"border-bottom:1px solid #aeaeae; padding: 10px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div><hr></td>\r\n");
      out.write("\t\t   \t\t</tr>\r\n");
      out.write("\t\t   \t\t<tr style=\"display:flex; align-items:center; justify-content:space-between;\">\r\n");
      out.write("\t\t   \t\t \t<td><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.link}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"border: 1px solid gray;\">상세정보</a></td>\r\n");
      out.write("\t\t   \t\t\t<td><button type=\"submit\" class=\"cartIn\">장바구니</button></td>\r\n");
      out.write("\t\t   \t\t\t<td><a id=\"buy_now\" style=\"background:#f5602a; color:white;\">바로 구매하기</a></td>\r\n");
      out.write("\t\t   \t\t</tr>\r\n");
      out.write("\t\t   </table>\r\n");
      out.write("\t\t   \r\n");
      out.write("\t   </div>\r\n");
      out.write("      \r\n");
      out.write("      <table style=\"display:none;\">\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td><input type=\"text\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("            <td><input type=\"text\" name=\"uid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("            <td><input type=\"text\" name=\"title\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("            <td><input type=\"text\" name=\"price\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("            <td><input type=\"text\" name=\"image\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("            <td><input type=\"text\" name=\"link\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.link}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      \r\n");
      out.write("   </form>\r\n");
      out.write("\r\n");
      out.write("   <div class=\"pagination\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"/resources/pagination.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar uid=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("   $(cart).on(\"submit\", function(e) {\r\n");
      out.write("      e.preventDefault();\r\n");
      out.write("      if (!confirm(\"장바구니에 넣으실래요?\")) return;\r\n");
      out.write("      var form = document.cart;\r\n");
      out.write("      \r\n");
      out.write("      form.submit();\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   $(\"#buy_now\").on(\"click\",function(e){\r\n");
      out.write("\t   \te.preventDefault();\r\n");
      out.write("\t   \r\n");
      out.write("\t   \tvar uid = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\tvar title = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\tvar price = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\tvar image='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\tvar link='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.link}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t   \r\n");
      out.write("\t   $.ajax({\r\n");
      out.write("\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\turl: \"/shop/buy\",\r\n");
      out.write("\t\t\tdata:{uid:uid,title:title,price:price,image:image,link:link},\r\n");
      out.write("\t\t\tsuccess:function(){\r\n");
      out.write("\t\t\t\tlocation.href=\"/cart/buy?uid=\"+uid;\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t   });\r\n");
      out.write("   });\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
