/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2022-05-18 15:30:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin.shop;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("@font-face {\r\n");
      out.write("    font-family: 'SBAggroL';\r\n");
      out.write("    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2108@1.1/SBAggroL.woff') format('woff');\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("    font-style: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#menu {\r\n");
      out.write("\tpadding:10px;\r\n");
      out.write("\tmargin: 0px auto;\r\n");
      out.write("\tfont-size: 30px;\r\n");
      out.write("\tfont-family: 'SBAggroL';\r\n");
      out.write("}\r\n");
      out.write("#menu td{\r\n");
      out.write("\tborder: 3px solid black;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<h1>\r\n");
      out.write("\t\t<a href=\"/admin/index\"><img src=\"/resources/AdminLogo.png\" style=\"width:90%; height :200px; margin:0px auto;\"></a>\r\n");
      out.write("\t</h1>\r\n");
      out.write("</head>\r\n");
      out.write("<table id=\"menu\" style=\"width:900px;\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><a href=\"/admin/shop/insert\">상품 등록</a></td>\t\t\r\n");
      out.write("\t\t\t<td><a href=\"/admin/shop/list\">상품 목록</a></td>\r\n");
      out.write("\t\t\t<td><a href=\"/admin/shop/alltrade\">주문 목록</a></td>\r\n");
      out.write("\t\t\t<td><a href=\"/admin/user/userlist\">유저 목록</a></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<div id=\"page\" style=\"margin:0px auto; text-align:center; font-family: 'SBAggroL';\">\r\n");
      out.write("   <h1>상품 등록</h1> \r\n");
      out.write("   <form name=\"shfrm\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("      <table style=\"margin:0px auto; text-align:center;\">\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td class=\"title\" width=100 style=\"margin:0px auto; text-align:center; border:3px solid black;\">상품사진</td>\r\n");
      out.write("            <td width=700 style=\"margin:0px auto; text-align:center; border:3px solid black;\">\r\n");
      out.write("               <img id=\"image\" name=\"image\" src=\"https://via.placeholder.com//300x200\" width=250/>\r\n");
      out.write("               <input type=\"file\" id=\"file\" name=\"file\" accept=\"image/* \"style=display:none;>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td class=\"title\" width=100 style=\"margin:0px auto; text-align:center; border:3px solid black;\">제목</td>\r\n");
      out.write("            <td width=400 style=\"margin:0px auto; text-align:center; border:3px solid black;\"><input type=\"text\" id=\"title\" name=\"title\" size=50></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("               <td class=\"price\" width=100 style=\"margin:0px auto; text-align:center; border:3px solid black;\">가격</td>\r\n");
      out.write("               <td width=300 style=\"margin:0px auto; text-align:center; border:3px solid black;\"><input type=\"text\" id=\"price\" name=\"price\" size=10></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      <div style=\"text-align:center;margin-top:20px;\">\r\n");
      out.write("         <input type=\"submit\" value=\"상품 올리기\">\r\n");
      out.write("         <input type=\"reset\" value=\"등록취소\" onClick=\"location.href='/admin/index'\">\r\n");
      out.write("      </div>\r\n");
      out.write("   </form>\r\n");
      out.write("</div>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("   $(shfrm).on(\"submit\", function(e){\r\n");
      out.write("      e.preventDefault();\r\n");
      out.write("      var title=$(\"#title\").val();\r\n");
      out.write("      var image=$(\"#file\").val();\r\n");
      out.write("      var price=$(\"#price\").val();\r\n");
      out.write("      \r\n");
      out.write("      if(image==\"\"){\r\n");
      out.write("         alert(\"사진을 등록하세요!\");\r\n");
      out.write("         return;\r\n");
      out.write("      }else if(title==\"\"){\r\n");
      out.write("         alert(\"제목을 입력하세요!\");\r\n");
      out.write("         $(\"#title\").focus();\r\n");
      out.write("         return;\r\n");
      out.write("      }else if(price==\"\" || price.replace(/[0-9]/g,'')){\r\n");
      out.write("         alert(\"가격을 숫자로 입력하세요!\");\r\n");
      out.write("         $(\"#price\").focus();\r\n");
      out.write("         return;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      if(!confirm(\"상품을 등록하실래요?\")) return;\r\n");
      out.write("      shfrm.submit();\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   $(\"#image\").on(\"click\", function(){\r\n");
      out.write("      $(\"#file\").click();\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   //이미지 미리보기\r\n");
      out.write("   $(\"#file\").on(\"change\", function(e){\r\n");
      out.write("      var file=$(\"#file\")[0].files[0];\r\n");
      out.write("      $(\"#image\").attr(\"src\", URL.createObjectURL(file));\r\n");
      out.write("   });\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
