/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2022-05-18 09:57:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.cart;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class buy_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("   <script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.iamport.kr/js/iamport.payment-1.1.5.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("#row {\r\n");
      out.write("\twidth: 900px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tmargin: 0px auto;\r\n");
      out.write("\tpointer:cursor;\r\n");
      out.write("}\r\n");
      out.write(".title,.price, .chk {\r\n");
      out.write("\tborder-right:1px solid #dedede;\r\n");
      out.write("\tborder-bottom:1px solid #dedede;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tpadding:10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title_buy {\r\n");
      out.write("\tbackground:#dedede;\r\n");
      out.write("\tpadding:5px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#cart {\r\n");
      out.write("\tmargin:0px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title_cart {\r\n");
      out.write("\tfont-size:30px;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("\tfont-family: 'SBAggroL';\r\n");
      out.write("\tmargin:0px auto;\r\n");
      out.write("\tmargin-top:100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#buy {\r\n");
      out.write("\tfont-family: 'SBAggroL';\r\n");
      out.write("\tbackground:#ed7753;\r\n");
      out.write("\tborder:none;\r\n");
      out.write("\tpadding:15px;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div id=\"page\">\r\n");
      out.write("   <table id=\"cart\"></table>\r\n");
      out.write("   <script id=\"temp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t <td colspan=2 class=\"title_buy\">상품 정보</td>\r\n");
      out.write("\t\t <td class=\"title_buy\">금액</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("   {{#each list}}\r\n");
      out.write("    <tr id=\"{{id}}\">\r\n");
      out.write("         <td><img src=\"/display?fileName={{image}}\" width=70 class=\"image\"></td>\r\n");
      out.write("         <td class=\"title row\" width=500>{{title}}</td>\r\n");
      out.write("\t\t <td class=\"price\">{{price}}</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("   {{/each}}\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td><h4 id=\"total\" sum={{sum}}>총합:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.sum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(",000원</h4></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("   </script>\r\n");
      out.write("   <br>\r\n");
      out.write("   <h2>배송지 입력</h2>\r\n");
      out.write("   <form name=\"frm2\" action=\"\" method=\"post\">\r\n");
      out.write("      <table style=\"margin:0px auto; text-align:center;\">\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td width=500>\r\n");
      out.write("                  <span class=\"titles\">주소</span>\r\n");
      out.write("                  <input type=\"text\" name=\"zipcode\" size=5 id=\"zipcode\" readonly>\r\n");
      out.write("                  <button type=\"button\" id=\"btn_search\" class=\"btn\">주소검색</button><br>\r\n");
      out.write("                  <input type=\"text\" name=\"uaddress1\" size=30 id=\"uaddress1\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.uaddress1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required><label> /</label>\r\n");
      out.write("                  <input type=\"text\" name=\"uaddress2\" size=10 id=\"uaddress2\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.uaddress2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"상세주소\"><br>\r\n");
      out.write("               </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("   </form>\r\n");
      out.write("   <button id=\"buy\" onclick=\"requestPay()\">상품주문</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var bid = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("   var page = 1;\r\n");
      out.write("   getList();\r\n");
      out.write("   \r\n");
      out.write("   $(\"#cart\").on(\"click\",\"#chkAll\",function(){\r\n");
      out.write("        var checked = $('#chkAll').is(':checked');\r\n");
      out.write("        if(checked){\r\n");
      out.write("           $('input:checkbox').prop('checked',true);\r\n");
      out.write("        }else{\r\n");
      out.write("           $('input:checkbox').prop('checked',false);   \r\n");
      out.write("        }\r\n");
      out.write("     });\r\n");
      out.write("   \r\n");
      out.write("   function getList() {\r\n");
      out.write("      $.ajax({\r\n");
      out.write("         type : \"get\",\r\n");
      out.write("         url : \"/cart/list.json\",\r\n");
      out.write("         data : {page : page, uid:bid},\r\n");
      out.write("         dataType : \"json\",\r\n");
      out.write("         success : function(data) {\r\n");
      out.write("            var template = Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("            $(\"#cart\").html(template(data));\r\n");
      out.write("            $(\".pagination\").html(getPagination(data));\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   //row를 클릭한경우\r\n");
      out.write("//       $(\"#cart\").on(\"click\", \".row\", function(){\r\n");
      out.write("//         var id=$(this).parent().attr(\"id\");\r\n");
      out.write("//         location.href=\"read?id=\" + id + \"&page=\" + page;\r\n");
      out.write("//       });\r\n");
      out.write("\r\n");
      out.write("   $(\".pagination\").on(\"click\", \"a\", function(e) {\r\n");
      out.write("      e.preventDefault();\r\n");
      out.write("      page = $(this).attr(\"href\");\r\n");
      out.write("      getList();\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("   var bno = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("   var uid = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("   var bsum ='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.sum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' + '000';\r\n");
      out.write("   var bname = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.uname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("   var bnickname='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.unickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("   var bemail='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.uemail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("   var bphone = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.uphone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("   var baddress =$(\"#uaddress1\").val() + \" \" + $(\"#uaddress2\").val();\r\n");
      out.write("   var btitle = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("   var bprice = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("   var bimage = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("   var blink = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.link}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("   \r\n");
      out.write("   //카카오결제API\r\n");
      out.write("   var IMP = window.IMP; // 생략 가능\r\n");
      out.write("      IMP.init(\"imp85774140\"); // 예: imp00000000\r\n");
      out.write("\r\n");
      out.write("   function requestPay() {\r\n");
      out.write("         alert(bno + bimage + blink + bsum);\r\n");
      out.write("      // IMP.request_pay(param, callback) 결제창 호출\r\n");
      out.write("      IMP.request_pay({ // param\r\n");
      out.write("         pg : \"kakaopay\",\r\n");
      out.write("         pay_method : \"card\",\r\n");
      out.write("         merchant_uid : 'merchant_' + new Date().getTime(),\r\n");
      out.write("         name : btitle,\r\n");
      out.write("         nickname : bnickname,\r\n");
      out.write("         amount : bsum,\r\n");
      out.write("         buyer_email : bemail,\r\n");
      out.write("         buyer_name : bname,\r\n");
      out.write("         buyer_tel : bphone,\r\n");
      out.write("         buyer_addr : baddress,\r\n");
      out.write("      }, function(rsp) { // callback\r\n");
      out.write("         if (rsp.success) { //결제성공\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                  type : \"post\",\r\n");
      out.write("                  url : \"/buy/insert\",\r\n");
      out.write("                  data : {bno:bno, uid:uid, bsum:bsum, bemail:bemail, btitle:btitle, bnickname:bnickname, bname:bname,\r\n");
      out.write("                     baddress:baddress, bphone:bphone, bimage:bimage, blink:blink},\r\n");
      out.write("                  success : function() {\r\n");
      out.write("                \t  $.ajax({\r\n");
      out.write("          \t\t\t\ttype: \"post\",\r\n");
      out.write("          \t\t\t\turl: \"/cart/deleteCart\",\r\n");
      out.write("          \t\t\t\tdata:{uid:uid},\r\n");
      out.write("          \t\t\t\tsuccess:function(){\r\n");
      out.write("          \t\t\t\t\talert(\"구매성공!\");\r\n");
      out.write("          \t\t\t\t}\r\n");
      out.write("          \t\t\t});\r\n");
      out.write("                 location.href = \"/\";\r\n");
      out.write("                  }\r\n");
      out.write("            });\r\n");
      out.write("         } else { //결제실패\r\n");
      out.write("            var msg = '결제에 실패하였습니다.';\r\n");
      out.write("             msg += '에러내용 : ' + rsp.error_msg;\r\n");
      out.write("             \r\n");
      out.write("             alert(msg);\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   //주소 검색후 값 적용\r\n");
      out.write("   $(\"#btn_search\").on(\"click\", function(){\r\n");
      out.write("      new daum.Postcode({\r\n");
      out.write("         oncomplete: function(data){\r\n");
      out.write("            $(\"#uaddress1\").val(data.address);\r\n");
      out.write("            $(\"#zipcode\").val(data.zonecode);\r\n");
      out.write("            $(\"#uaddress1\").focus();\r\n");
      out.write("         }\r\n");
      out.write("      }).open();   \r\n");
      out.write("   });\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
