/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2022-05-18 00:52:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.pet;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t#page {\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.pet_img {\r\n");
      out.write("\t\twidth : 300px;\r\n");
      out.write("\t\theight : 330px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.pet_img:hover {\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.pet:hover > .pet_title {\r\n");
      out.write("\t\ttransition: display .5s;\r\n");
      out.write("\t\tdisplay:block;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#list {\r\n");
      out.write("\t\twidth:1500px; \r\n");
      out.write("\t\toverflow:hidden; \r\n");
      out.write("\t\tmargin:0px auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t.pet {\r\n");
      out.write("\t\twidth: 300px; \r\n");
      out.write("\t\tfloat:left; \r\n");
      out.write("\t\tmargin:30px;\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t\toverflow:hidden;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.pet_title {\r\n");
      out.write("\t\tdisplay:none;\r\n");
      out.write("\t\twidth:300px;\r\n");
      out.write("\t\tbackground:black;\r\n");
      out.write("\t\topacity: 0.5;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tpadding:10px;\r\n");
      out.write("\t\ttop:88%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#category_select {\r\n");
      out.write("\t\tborder: 1px solid #aeaeae;\r\n");
      out.write("\t\tpadding :7px 20px 7px 0px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\toption {\r\n");
      out.write("\t\tfont-size:17px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#search_box{\r\n");
      out.write("\t\tborder: 1px solid #aeaeae;\r\n");
      out.write("\t\tpadding :7px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#search_box:focus{\r\n");
      out.write("\t\toutline:none;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#search_pet_btn {\r\n");
      out.write("\t\tborder: 1px solid #aeaeae;\r\n");
      out.write("\t\tbackground: white;\r\n");
      out.write("\t\tpadding:7px 30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.header_dictionary {\r\n");
      out.write("\t\twidth:500px;\r\n");
      out.write("\t\tmargin :0px auto;\r\n");
      out.write("\t\tdisplay:flex;\r\n");
      out.write("\t\tjustify-content: center;\r\n");
      out.write("\t\tjustify-content: space-between;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("<div style=\"text-align:center;position: relative; margin-bottom:70px;\">\r\n");
      out.write("\t<img src=\"/resources/dog_img/dictionary_banner.png\" style=\"height:500px; width:100%;\">\r\n");
      out.write("\t<div class=\"body_banner\"> \r\n");
      out.write("\t\t<div class=\"heading\">\r\n");
      out.write("\t\t  <div>\r\n");
      out.write("\t\t    <p id=\"banner_top\" class=\"slide-up\">All PET</p>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"notosanskr\">\r\n");
      out.write("\t\t    <p id=\"banner_bottom\" class=\"slide-up\">반려동물의 정보들을 신속하게 알려드립니다</p>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div> \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"header_board\">\r\n");
      out.write("\t<a id=\"freeBoard\" href=\"/pet/list\">반려 지식백과</a>\r\n");
      out.write("\t<a id=\"petStar\" href=\"/symptom/list\">증상 지식백과</a>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"page\" style=\"text-align:center;\">\r\n");
      out.write("\t<p class=\"small_title\">반려 지식백과</p>\r\n");
      out.write("\t<p class=\"big_title\">함께 살 반려동물들을 알아보세요 </p>\r\n");
      out.write("\t<!--헤더 -->\r\n");
      out.write("\t<div class=\"header_dictionary\">\r\n");
      out.write("\t\t<select id=\"category_select\">\r\n");
      out.write("\t\t\t<option value=\"all\">전체</option>\r\n");
      out.write("\t\t\t<option value=\"dog\">견종</option>\r\n");
      out.write("\t\t\t<option value=\"cat\">묘종</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<input type=\"text\" size=40 id=\"keyword\">\r\n");
      out.write("\t\t<input type=\"text\" style=\"display:none\">\r\n");
      out.write("\t\t<input type=\"button\" id=\"search_pet_btn\" value=\"검색\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 메인 페이지 -->\r\n");
      out.write("\t<div id=\"list\"></div>\r\n");
      out.write("\t<script id=\"temp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t{{#each list}}\r\n");
      out.write("\t\t<div class=\"pet\" onClick=\"location.href='/pet/read?dno={{dno}}'\">\r\n");
      out.write("\t\t\t<img src=\"/display?fileName={{dimage}}\" class=\"pet_img\">\r\n");
      out.write("\t\t\t<p class=\"pet_title\">{{dtitle}}</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t{{/each}}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"pagination\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar searchform = $(\"#category_select\");\r\n");
      out.write("\tvar searchType = searchform.find(\"option:selected\").val();\r\n");
      out.write("\tvar page=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.page==null?1:param.page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\tvar keyword=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.keyword==null?'':param.keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("\tgetList();\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getList(){\r\n");
      out.write("\t\tsearchType = searchform.find(\"option:selected\").val();\r\n");
      out.write("\t\tkeyword= $(\"#keyword\").val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype: \"get\",\r\n");
      out.write("\t\t\turl: \"/pet/list.json\",\r\n");
      out.write("\t\t\tdata: {page:page, keyword:keyword,searchType : searchType},\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\tvar template = Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("\t\t\t\t$(\"#list\").html(template(data));\r\n");
      out.write("\t\t\t\t$(\".pagination\").html(getPagination(data));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//검색버튼을 클릭한 경우\r\n");
      out.write("   $(\"#search_pet_btn\").on(\"click\", function(){\r\n");
      out.write("\t  alert(\"검색\"+keyword);\r\n");
      out.write("      page=1;\r\n");
      out.write("      getList();\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   //검색어상자에서 엔터를 친경우\r\n");
      out.write("   $(\"#keyword\").on(\"keypress\", function(e){\r\n");
      out.write("\t   if(e.keyCode==13) $(\"#search_pet_btn\").click();\r\n");
      out.write("   });\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".pagination\").on(\"click\", \"a\", function(e){\r\n");
      out.write("\t\te.preventDefault();\r\n");
      out.write("\t\tpage=$(this).attr(\"href\");\r\n");
      out.write("\t\tgetList();\r\n");
      out.write("\t});\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
