/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2022-05-18 00:29:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.qna;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<link href=\"/resources/board.css\" rel=\"stylesheet\" >\r\n");
      out.write("<style>\r\n");
      out.write("\t#board_footer {\r\n");
      out.write("\t\tmargin:0px auto;\r\n");
      out.write("\t\twidth:1150px;\r\n");
      out.write("\t\ttext-align:right;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#banner_top {\r\n");
      out.write("\t\tmargin-left:150px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.wait {\r\n");
      out.write("\t\tfont-size:13px;\r\n");
      out.write("\t\twidth:80px;\r\n");
      out.write("\t\tborder:1px solid #aeaeae;\r\n");
      out.write("\t\tborder-radius:10px;\r\n");
      out.write("\t\tcolor:#aeaeae;\r\n");
      out.write("\t\tmargin:0px auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.complete {\r\n");
      out.write("\t\tfont-size:13px;\r\n");
      out.write("\t\twidth:80px;\r\n");
      out.write("\t\tborder:1px solid #d69c7c;\r\n");
      out.write("\t\tbackground:#d69c7c;\r\n");
      out.write("\t\tborder-radius:10px;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\tmargin:0px auto;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<div style=\"text-align:center;position: relative; margin-bottom:70px;\">\r\n");
      out.write("   <img src=\"/resources/qna_banner.png\" style=\"height:500px; width:100%;\">\r\n");
      out.write("   <div class=\"body_banner\"> \r\n");
      out.write("      <div class=\"heading\">\r\n");
      out.write("        <div>\r\n");
      out.write("          <p id=\"banner_top\" class=\"slide-up\">고객센터</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"notosanskr\">\r\n");
      out.write("          <p id=\"banner_bottom\" class=\"slide-up\">강아지,고양이 입양 상담 . 무엇이든 물어봐주세요</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div> \r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"board_content\">\r\n");
      out.write("   <p class=\"small_title\">QnA</p>\r\n");
      out.write("   <p class=\"big_title\">자유롭게 질문해주세요</p>\r\n");
      out.write("   <table id=\"tbl_board\"></table>\r\n");
      out.write("\t<script id=\"temp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t<tr class=\"title\">\r\n");
      out.write("\t\t<td width=100>번호</td>\r\n");
      out.write("\t\t<td width=400>제목</td>\r\n");
      out.write("\t\t<td iwdth=100>작성자</td>\r\n");
      out.write("\t\t<td width=250>날짜</td>\r\n");
      out.write("\t\t<td width=150>상태</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("   {{#each list}}\r\n");
      out.write("      <tr class=\"row_board\">\r\n");
      out.write("        <td class=\"bno\">{{qno}}</td>\t\r\n");
      out.write("        <td class=\"btitle\">{{qtitle}}</td>\r\n");
      out.write("\t\t<td><p class=\"writer\">{{qwriter}}</p></td>\r\n");
      out.write("\t\t<td>{{qdate}}</td>\r\n");
      out.write("\t\t<td><p class=\"{{style qstatus}}\">{{display qstatus}}</p></td> \r\n");
      out.write("      </tr>\r\n");
      out.write("   {{/each}}\r\n");
      out.write("   </script>\r\n");
      out.write("   <script>\r\n");
      out.write("\t\tHandlebars.registerHelper(\"display\", function(qstatus){\r\n");
      out.write("\t\t\tif(qstatus==0){\r\n");
      out.write("\t\t\t\treturn \"답변대기\";\r\n");
      out.write("\t\t\t}else if(qstatus==1){\r\n");
      out.write("\t\t\t\treturn \"답변완료\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tHandlebars.registerHelper(\"style\", function(qstatus){\r\n");
      out.write("\t\t\tif(qstatus==0){\r\n");
      out.write("\t\t\t\treturn \"wait\";\r\n");
      out.write("\t\t\t}else if(qstatus==1){\r\n");
      out.write("\t\t\t\treturn \"complete\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>   \r\n");
      out.write("   \t<div id=\"board_footer\">\r\n");
      out.write("   \t\t<a href=\"/qna/insert\" >게시글 작성</a>\r\n");
      out.write("   \t</div>\r\n");
      out.write("   <div class=\"pagination\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"/resources/pagination.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar keyword=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.keyword==null?'':param.keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\r\n");
      out.write("\tvar page = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.page==null ? 1: param.page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\tgetList();\r\n");
      out.write("\tfunction getList() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\turl : \"/qna/list.json\",\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\tpage : page\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tvar template = Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("\t\t\t\t$(\"#tbl_board\").html(template(data));\r\n");
      out.write("\t\t\t\t$(\".pagination\").html(getPagination(data));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//row를 클릭한경우\r\n");
      out.write("\t   $(\"#tbl_board\").on(\"click\", \".row_board\", function(){\r\n");
      out.write("\t\t  var qno=$(this).find(\".bno\").html();\r\n");
      out.write("\t\t  location.href=\"read?qno=\" + qno ;\r\n");
      out.write("\t   });\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".pagination\").on(\"click\", \"a\", function(e){\r\n");
      out.write("\t      e.preventDefault();\r\n");
      out.write("\t      page=$(this).attr(\"href\");\r\n");
      out.write("\t      getList();\r\n");
      out.write("\t   });\r\n");
      out.write("\t\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
