/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2022-05-18 00:40:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mypet;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<div class=\"page\">\r\n");
      out.write("\t<h1>사진 등록</h1>\r\n");
      out.write("\t<form name=\"mpfrm\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"uimage\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" size=80>\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"title\" width=100>사진</td>\r\n");
      out.write("\t\t\t\t<td width=700>\r\n");
      out.write("\t\t\t\t\t<img id=\"mpimage\" name=\"mpimage\" src=\"https://via.placeholder.com//300x200\" width=250/>\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" id=\"file\" name=\"file\" accept=\"image/* \"style=display:none;>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"title\" width=100>제목 :</td>\r\n");
      out.write("\t\t\t\t<td width=600><input type=\"text\" id=\"mptitle\" name=\"mptitle\" size=80></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("            <td class=\"mpwriter\" width=100>작성자</td>\r\n");
      out.write("            <td width=300><input type=\"text\" name=\"mpwriter\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${unickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" size=10 readonly></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"title\" width=100>내용</td>\r\n");
      out.write("\t\t\t\t<td width=700>\r\n");
      out.write("\t\t\t\t\t<textarea rows=\"10\" cols=\"80\" id=\"mpcontent\" name=\"mpcontent\"></textarea>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<div style=\"text-align:center;margin-top:20px;\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"사진 올리기\">\r\n");
      out.write("\t\t\t<input type=\"reset\" value=\"등록취소\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(mpfrm).on(\"submit\", function(e){\r\n");
      out.write("\t\te.preventDefault();\r\n");
      out.write("\t\tvar mptitle=$(\"#mptitle\").val();\r\n");
      out.write("\t\tvar mpcontent=$(\"#mpcontent\").val();\r\n");
      out.write("\t\tvar mpimage=$(\"#file\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(mpimage==\"\"){\r\n");
      out.write("\t\t\talert(\"사진을 등록하세요!\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}else if(mptitle==\"\"){\r\n");
      out.write("\t\t\talert(\"제목을 입력하세요!\");\r\n");
      out.write("\t\t\t$(\"#mptitle\").focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}else if(mpcontent==\"\"){\r\n");
      out.write("\t\t\talert(\"내용을 입력하세요!\");\r\n");
      out.write("\t\t\t$(\"#mpcontent\").focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(!confirm(\"사진을 등록하실래요?\")) return;\r\n");
      out.write("\t\tmpfrm.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\"#mpimage\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#file\").click();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t//이미지 미리보기\r\n");
      out.write("\t$(\"#file\").on(\"change\", function(e){\r\n");
      out.write("\t\tvar file=$(\"#file\")[0].files[0];\r\n");
      out.write("\t\t$(\"#mpimage\").attr(\"src\", URL.createObjectURL(file));\r\n");
      out.write("\t});\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
