/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2022-05-19 01:20:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t#about {\r\n");
      out.write("\t}\r\n");
      out.write("\t.box {\r\n");
      out.write("\t\twidth:450px;\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t}\r\n");
      out.write("\t.row {\r\n");
      out.write("\tdisplay:flex;\r\n");
      out.write("\tflex-direction:column;\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tmargin:5px;\r\n");
      out.write("\twidth:320px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tborder: 1px solid #dedede;\r\n");
      out.write("\theight: 400px;\r\n");
      out.write("\tjustify-content:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row:hover {\r\n");
      out.write("\tcursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shop_image {\r\n");
      out.write("\twidth:300px;\r\n");
      out.write("\theight:300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#shop {\r\n");
      out.write("\tmargin : 0px auto;\r\n");
      out.write("\twidth:1350px;\r\n");
      out.write("\tpadding-right:-10px;\r\n");
      out.write("\tmargin-bottom:100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".price {\r\n");
      out.write("\tfont-size:22px;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#banner_top {\r\n");
      out.write("\tmargin-left:130px;\r\n");
      out.write("}\r\n");
      out.write("#tbl_board {\r\n");
      out.write("\tmargin:0px auto;\r\n");
      out.write("\tmargin-bottom:100px;\r\n");
      out.write("}\t\r\n");
      out.write("\r\n");
      out.write("#tbl_board td {\r\n");
      out.write("\tpadding:15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tbl_board .title {\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tbackground:#EEEEEE;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("\tborder-top:1px solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#board_content {\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tbl_board .row_board {\r\n");
      out.write("\tborder-top:1px solid #dedede;\r\n");
      out.write("\tborder-bottom:1px solid #dedede;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mypet {\r\n");
      out.write("   width: 900px;\r\n");
      out.write("   margin: 0px auto;\r\n");
      out.write("   overflow: hidden;\r\n");
      out.write("   margin-bottom:100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#pet_box {\r\n");
      out.write("   width: 280px;\r\n");
      out.write("   height:350px;\r\n");
      out.write("   margin: 10px;\r\n");
      out.write("   float: left;\r\n");
      out.write("   border: 1px solid #cecece;\r\n");
      out.write("   cursor: pointer;\r\n");
      out.write("   border-radius:10px;\r\n");
      out.write("   font-family: 'SBAggroL';\r\n");
      out.write("   background:white;\r\n");
      out.write("   overflow:hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".petBox_content {\r\n");
      out.write("\tpadding : 10px;\r\n");
      out.write("\tdisplay:flex;\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("\ttext-align:left;\r\n");
      out.write("\tfont-size:17px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#shop .title {\r\n");
      out.write("   width: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal2 \r\n");
      out.write("{ \r\n");
      out.write("\tposition: absolute; top: 0; left: 0; width: 100%; height:1700px; \r\n");
      out.write("\tdisplay: none; background-color: rgba(0, 0, 0, 0.4); \r\n");
      out.write("\tz-index:20;\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write(".modal_body2\r\n");
      out.write("{ \r\n");
      out.write("\tposition: absolute; top: 50%; left: 50%; width: 1000px; \r\n");
      out.write("\theight: 400px; text-align: center; background-color: rgb(255, 255, 255); border-radius: 10px; \r\n");
      out.write("\tbox-shadow: 0 2px 3px 0 rgba(34, 36, 38, 0.15); \r\n");
      out.write("\ttransform: translateX(-50%) translateY(-50%); \r\n");
      out.write("\tmargin:0px auto;\r\n");
      out.write("\tpadding : 50px;\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-close2 {\r\n");
      out.write("   width: 20px;\r\n");
      out.write("   height: 20px;\r\n");
      out.write("   float: right;\r\n");
      out.write("   cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".big_title {\r\n");
      out.write("\ttransform: translateY(-30px);\r\n");
      out.write("\tbackground-color:white;\r\n");
      out.write("\twidth:200px;\r\n");
      out.write("\tmargin:0px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".small_title {\r\n");
      out.write("\ttransform: translateY(-10px);\r\n");
      out.write("\tmargin-top:50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".plusView2 {\r\n");
      out.write("\tpadding:20px 50px;\r\n");
      out.write("\tbackground:#232323;\r\n");
      out.write("\tborder:none;\r\n");
      out.write("\tfont-family: 'SBAggroL';\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tfont-size:18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".plusView {\r\n");
      out.write("\tpadding:20px 50px;\r\n");
      out.write("\tbackground:#f77b52;\r\n");
      out.write("\tborder:none;\r\n");
      out.write("\tfont-family: 'SBAggroL';\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tfont-size:18px;\r\n");
      out.write("\tmargin-bottom:100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<div id=\"about\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "slick.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div><p class=\"small_title\">new product</p></div>\r\n");
      out.write("\t<div style=\"display:relative; text-align:center;\">\r\n");
      out.write("\t\t<p style=\"border:1px solid #232323; display:relative; z-index:-1;\"></p>\r\n");
      out.write("\t\t<div class=\"big_title\">신규 상품</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("   \t<table id=\"shop\"></table>\r\n");
      out.write("\t<script id=\"temp2\" type=\"text/x-handlebars-template\">\r\n");
      out.write("   {{#each .}}\r\n");
      out.write("      <tr class=\"row\" id=\"{{id}}\">\r\n");
      out.write("         <td ><img src=\"/display?fileName={{image}}\" class=\"shop_image\"></td><br>\r\n");
      out.write("         <td class=\"title\">{{title}}</td><br>\r\n");
      out.write("\t\t <td class=\"price\">{{price}}</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("   {{/each}}\r\n");
      out.write("   </script>\r\n");
      out.write("   \r\n");
      out.write("   <button onClick=\"location.href='/shop/list'\" class=\"plusView\">더보기 + </button>\r\n");
      out.write("     \r\n");
      out.write("\t<div style=\"background:#ff865e; height:800px; padding:10px;\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div><p class=\"small_title\" style=\"color:#e6bd8e\">best pets</p></div>\r\n");
      out.write("\t\t\t<div style=\"display:relative; text-align:center; color:white\">\r\n");
      out.write("\t\t\t\t<p style=\"border:1px solid white; display:relative; z-index:-1;\"></p>\r\n");
      out.write("\t\t\t\t<div class=\"big_title\" style=\"background:#ff865e;\">인기 포포펫</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"mypet\"></div>\r\n");
      out.write("\t\t\t<button onClick=\"location.href='/mypet/list'\" class=\"plusView2\">더보기 + </button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t   <script id=\"temp3\" type=\"text/x-handlebars-template\">\r\n");
      out.write("   {{#each .}}\r\n");
      out.write("      <div id=\"pet_box\" class=\"btn-open-popup2\">   \r\n");
      out.write("         \t<p class=\"mpno\" style=display:none;>{{mpno}}</p>\r\n");
      out.write("\t\t\t<p class=\"uimage\" style=display:none;>{{uimage}}</p>\r\n");
      out.write("\t\t\t<p class=\"likeImg\" style=display:none;>{{likeImg}}</p>\r\n");
      out.write("         \t<p class=\"mpimage\" style=display:none;>{{mpimage}}</p>      \r\n");
      out.write("         \t<img src=\"/display?fileName={{mpimage}}\" style=\"width:280px; height:250px;\" >\r\n");
      out.write("         \t<div class=\"petBox_content\">\r\n");
      out.write("\t\t\t\t<div><b class=\"mpwriter\">{{mpwriter}}</b>&nbsp;&nbsp;<span class=\"mptitle\">{{mptitle}}</span></div>\r\n");
      out.write("\t\t\t\t<div style=\"display:flex;\">좋아요 <p class=\"mpcount\" id=\"mpnum\">{{mpcount}}</p>개</div>\t\t\t\t\r\n");
      out.write("         \t\t<p class=\"mpregdate\">{{mpregdate}}</p>\r\n");
      out.write("\t\t \t</div>\r\n");
      out.write("      \t</div>\r\n");
      out.write("   {{/each}}\r\n");
      out.write("   </script>\r\n");
      out.write("   \r\n");
      out.write("   <div><p class=\"small_title\">best article</p></div>\r\n");
      out.write("\t<div style=\"display:relative; text-align:center;\">\r\n");
      out.write("\t\t<p style=\"border:1px solid #232323; display:relative; z-index:-1;\"></p>\r\n");
      out.write("\t\t<div class=\"big_title\">인기 글</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("   \r\n");
      out.write("   <table id=\"tbl_board\"></table>\r\n");
      out.write("\t<script id=\"temp1\" type=\"text/x-handlebars-template\">\r\n");
      out.write("      {{#each .}}\r\n");
      out.write("       <tr class=\"row_board\">\r\n");
      out.write("         <td class=\"bno\">{{bno}}</td>\r\n");
      out.write("         <td class=\"btitle\">{{btitle}}</td>\r\n");
      out.write("         <td>{{bwriter}}</td>\r\n");
      out.write("         <td>{{bregdate}}</td>\r\n");
      out.write("\t\t <td>{{bcount}}</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      {{/each}}\r\n");
      out.write("   </script>\r\n");
      out.write("   \r\n");
      out.write("   <button onClick=\"location.href='/board/list'\" class=\"plusView\">더보기 + </button>\r\n");
      out.write("   \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tgetList();\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getList() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\turl : \"/board.json\",\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tvar temp = Handlebars.compile($(\"#temp1\").html());\r\n");
      out.write("\t\t\t\t$(\"#tbl_board\").html(temp(data));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\turl : \"/shop.json\",\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tvar template = Handlebars.compile($(\"#temp2\").html());\r\n");
      out.write("\t\t\t\t$(\"#shop\").html(template(data));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\turl : \"/mypet.json\",\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tvar template = Handlebars.compile($(\"#temp3\").html());\r\n");
      out.write("\t\t\t\t$(\"#mypet\").html(template(data));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//board row를 클릭한경우\r\n");
      out.write("\t$(\"#tbl_board\").on(\r\n");
      out.write("\t\t\t\"click\",\r\n");
      out.write("\t\t\t\".row_board\",\r\n");
      out.write("\t\t\tfunction() {\r\n");
      out.write("\t\t\t\tvar bno = $(this).find(\".bno\").html();\r\n");
      out.write("\t\t\t\tlocation.href = \"board/read?bno=\" + bno + \"&page=\" + 1\r\n");
      out.write("\t\t\t\t\t\t+ \"&keyword=\" + \"\";\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//shop row를 클릭한경우\r\n");
      out.write("\t   $(\"#shop\").on(\"click\", \".row\", function(){\r\n");
      out.write("\t     var id=$(this).attr(\"id\");\r\n");
      out.write("\t     location.href=\"shop/read?id=\" + id + \"&page=\" + 1;\r\n");
      out.write("\t   });\r\n");
      out.write("\t\r\n");
      out.write("\t//mypet row를 클릭한경우\r\n");
      out.write("\t$(\"#mypet\").on(\"click\", function(){\r\n");
      out.write("\t\tlocation.href=\"mypet/list\";\r\n");
      out.write("\t});\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
